# Generated by Django 5.0.6 on 2024-06-06 19:59

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['id', 'slug', 'phone', 'user']},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id', 'slug', 'phone', 'user']},
        ),
        migrations.AddField(
            model_name='doctor',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
