# Generated by Django 5.0.6 on 2024-06-05 05:20

import mdeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='description',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
