# Generated by Django 5.0.6 on 2024-06-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_doctor_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='api.category'),
        ),
    ]
