# Generated by Django 5.0.6 on 2024-06-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image of the medication', upload_to='medications/%Y/%m/%d/'),
        ),
    ]
