# Generated by Django 5.0.6 on 2024-06-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_medication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id', 'slug'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['id', 'slug', 'price']},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', help_text='A short label, generally used in URLs.', verbose_name='URL'),
        ),
        migrations.AddField(
            model_name='medication',
            name='slug',
            field=models.SlugField(default='', help_text='A short label, generally used in URLs.', verbose_name='URL'),
        ),
    ]
