# Generated by Django 5.0.6 on 2024-06-06 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medication_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', help_text='A short label, generally used in URLs.', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='slug',
            field=models.SlugField(default='', help_text='A short label, generally used in URLs.', unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='A short label, generally used in URLs.', unique=True, verbose_name='URL')),
                ('address', models.CharField(max_length=125)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
