# Generated by Django 5.0.6 on 2024-06-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_medication_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id', 'slug', 'name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='', help_text='A short label, generally used in URLs.', unique=True, verbose_name='URL'),
        ),
    ]
