# Generated by Django 5.0.6 on 2024-06-06 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_slug_alter_medication_slug_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id', 'slug']},
        ),
        migrations.AddField(
            model_name='patient',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this object should be treated as active. Unselect this instead of deleting objects.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='slug',
            field=models.SlugField(default='', help_text='A short label, generally used in URLs.', unique=True, verbose_name='URL'),
        ),
    ]
