# Generated by Django 5.0.6 on 2024-06-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_patient_options_patient_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
