# Generated by Django 5.0.6 on 2024-06-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_user_reset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_code',
            field=models.CharField(blank=True, max_length=7, null=True, unique=True),
        ),
    ]
